### ISSUE TITLE
Can an I-ADOPT variable be connected to 2 related concepts from 2 different source vocabularies for e.g. properties or should we only allow 1 

### ISSUE THREAD

**Issue by gwemon** [i-adopt/questions#2]
Our example is:
We have the CF standard name: [mass_fraction_of_chlorophyll_a_in_sea_water](http://vocab.nerc.ac.uk/collection/P07/current/ORZ7DVDT/)
which we are in the process of expressing according to the I-ADOPT model. We have 2 options:

1) since this is effectively "Concentration of X in medium Y", we could use the NVS concept: [Concentration](http://vocab.nerc.ac.uk/collection/S06/current/S0600045/) as the I-ADOPT property;
2) or we can use the closer matching QUDT concept: [Mass fraction](http://qudt.org/vocab/quantitykind/MassFraction)

My question is: can we use both mappings? 
or do we have to choose one, probably preferably the more closely matched QUDT concept http://qudt.org/vocab/quantitykind/MassFraction, and have that concept mapped to the NVS concept    
http://vocab.nerc.ac.uk/collection/S06/current/S0600045/ by a BRD/NAR relationship to enable interoperability between datasets that use the term "Concentration" and datasets that use the term "Mass fraction"?

@mabablue @SirkoS @alko-k FYI

**Comment by SirkoS** [comment]
From the ontology definition itself, you can only use one `Property` per `Variable`. The intention was not to have all atomic `Property`s linked to a variable but break a `Variable` down to something that can be more easily (and unambiguously) be matched. So for aligning catalogs of `Variable`s, we will actually have to align the underlying vocabularies of atomic components. 

As you already noted, the QUDT concept is the more accurate one. So I'd go for that.

The NVS concept `Concentration`, strictly speaking, is somewhat ill-defined in my opinion. Even from the first few examples, there are some using this for a `concentration ... per unit mass` and a `concentration ... per unit volume` (and later `concentration ... per unit dry weight`). For human users that are "only" searching for concepts and associated datasets, this likely does not really matter. For automated access this might mix up things that should not be mixed.

If you want to use NVS concepts, I'd likely create sub-concepts for `Concentration` using `Concentration per Unit Mass` etc. and link those sub-concepts to the actual `Variable`s. That way, you would have a more accurate description and keep the current behavior in search for your users.

**Comment by gwemon** [comment]
Thank you @SirkoS. Yes I agree that according to the ontology definition we can only have one property per variable. We will need to carefully control this in our implementation. I would not, at this stage consider changing any of the existing vocabs but instead try an implementation that is as close to the source term as possible then build the relationships between the underlying vocabularies separately. We will try that in the few pilots we are currently working on.

**Comment by gwemon** [comment]
> From the ontology definition itself, you can only use one `Property` per `Variable`. The intention was not to have all atomic `Property`s linked to a variable but break a `Variable` down to something that can be more easily (and unambiguously) be matched. So for aligning catalogs of `Variable`s, we will actually have to align the underlying vocabularies of atomic components.
> 
> As you already noted, the QUDT concept is the more accurate one. So I'd go for that.
> 
> The NVS concept `Concentration`, strictly speaking, is somewhat ill-defined in my opinion. Even from the first few examples, there are some using this for a `concentration ... per unit mass` and a `concentration ... per unit volume` (and later `concentration ... per unit dry weight`). For human users that are "only" searching for concepts and associated datasets, this likely does not really matter. For automated access this might mix up things that should not be mixed.
> 
> If you want to use NVS concepts, I'd likely create sub-concepts for `Concentration` using `Concentration per Unit Mass` etc. and link those sub-concepts to the actual `Variable`s. That way, you would have a more accurate description and keep the current behavior in search for your users.

Following consideration I agree with you @SirkoS that we will need to create these property concepts you suggested "Concentration per unit volume" and "Concentration per unit mass" as single entities in our S06 property vocabulary. Without them close alignment with other vocabs will be difficult.

**Comment by mabablue** [comment]
Hi all, please check this pattern - https://github.com/i-adopt/patterns/blob/main/quantitative/concentration.md where this is explained in a more precise way
